/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author proxc
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     *
     * /**
     * The text field that stores the login the user has written
     */
    private JFrame homeFrame;

    public Home() {
        initComponents();
        homeFrame = this;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(false);
                Home homeFrame = new Home();
                homeFrame.setLocation(450, 175); // Set the location of the frame to (100, 100)
                homeFrame.setVisible(true);

            }
        });
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        passwordText = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        loginText = new javax.swing.JLabel();
        databaseUrlField = new javax.swing.JTextField(Translator.getValue("databaseUrlText"));
        loginField = new javax.swing.JTextField(Translator.getValue("loginText"));
        passwordField = new javax.swing.JPasswordField(Translator.getValue("passwordText"));
        databaseUrlText = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        connectButton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        connectButton1 = new javax.swing.JButton();
        ChangeLanguageButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menubar1 = new javax.swing.JMenu();
        newWindow = new javax.swing.JMenuItem();
        HistoryMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("sms");
        setBounds(new java.awt.Rectangle(500, 200, 420, 500));
        setMaximizedBounds(new java.awt.Rectangle(500, 200, 0, 0));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(640, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(854, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 22, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/navigation.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, -10, 90, 100));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("SMS");
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 170, 70));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/navigation.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -10, 90, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 80));

        passwordText.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        passwordText.setText("Password");
        jPanel1.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 120, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel16.setText(":");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 20, 30));

        loginText.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        loginText.setText("Username");
        jPanel1.add(loginText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 120, 30));

        databaseUrlField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        databaseUrlField.setText("jdbc:mysql://localhost:3306/");
        databaseUrlField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databaseUrlFieldActionPerformed(evt);
            }
        });
        jPanel1.add(databaseUrlField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 260, 30));

        loginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFieldActionPerformed(evt);
            }
        });
        jPanel1.add(loginField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 260, 30));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 260, 30));

        databaseUrlText.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        databaseUrlText.setText("Database URL");
        jPanel1.add(databaseUrlText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 170, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel20.setText(":");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 20, 30));

        connectButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        jPanel1.add(connectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel19.setText(":");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 20, 30));

        connectButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        connectButton1.setText("Connect");
        connectButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(connectButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        ChangeLanguageButton.setText("Change Language");
        ChangeLanguageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeLanguageButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ChangeLanguageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));

        menubar1.setText("File");

        newWindow.setText("New Window");
        newWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWindowActionPerformed(evt);
            }
        });
        menubar1.add(newWindow);

        HistoryMenuItem.setText("History");
        HistoryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryMenuItemActionPerformed(evt);
            }
        });
        menubar1.add(HistoryMenuItem);

        jMenuBar1.add(menubar1);
        menubar1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                addNewInternalFrame();
            }
        });

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 640, 473);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void loginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFieldActionPerformed

    private void databaseUrlFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databaseUrlFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_databaseUrlFieldActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // TODO add your handling code here:
        if (loginField.getText().equals("") || databaseUrlField.getText().equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), Translator.getValue("fillEmptyFields"),
                    Translator.getValue("error"),
                    JOptionPane.ERROR_MESSAGE);
        } else {
            // Get login, password and database url from fields and set them for database
            // handler
            DBHandler.setLogin(loginField.getText());
            DBHandler.setPassword(passwordField.getText());
            DBHandler.setDatabaseUrl(databaseUrlField.getText());

            // If table has\hasn't been successfully created then inform the user about that
            if (DBHandler.createTables()) {
                JOptionPane.showMessageDialog(new JFrame(), "Connection success.",
                        "Information", JOptionPane.INFORMATION_MESSAGE);

                // Open a new window where you can manage the table and close the old one
                ManagementView.main(null);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Connection error.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_connectButtonActionPerformed

    private void newWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWindowActionPerformed
        // TODO add your handling code here:
        JFrame newFrame = new JFrame("New Window");
        newFrame.setContentPane(homeFrame.getContentPane());
        newFrame.pack();
        newFrame.setLocationRelativeTo(null);
        newFrame.setVisible(true);
    }//GEN-LAST:event_newWindowActionPerformed

    private void HistoryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryMenuItemActionPerformed
        // TODO add your handling code here:
        addNewInternalFrame();
    }//GEN-LAST:event_HistoryMenuItemActionPerformed

    private void connectButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_connectButton1ActionPerformed

    private void ChangeLanguageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeLanguageButtonActionPerformed
        // TODO add your handling code here:
        Language selectedLanguage = (Language) JOptionPane.showInputDialog(null, Translator.getValue("sms"),
                Translator.getValue("selectLanguage"), JOptionPane.QUESTION_MESSAGE, null, Language.values(),
                Language.ENG.toString());

        if (selectedLanguage != null) {
            Translator.setLanguage(selectedLanguage);
        } else {
            return;
        }

        Translator.getMessagesFromXML();

        homeFrame.dispose();
        new Home();
    }//GEN-LAST:event_ChangeLanguageButtonActionPerformed
    int xx, xy;

    public void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(197, 197, 197));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(240, 240, 240));
    }

    private void addNewInternalFrame() {
        MyInternalFrame internalFrame = new MyInternalFrame("New Internal Frame");
        homeFrame.add(internalFrame);
        internalFrame.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeLanguageButton;
    private javax.swing.JMenuItem HistoryMenuItem;
    private javax.swing.JButton connectButton;
    private javax.swing.JButton connectButton1;
    private javax.swing.JTextField databaseUrlField;
    private javax.swing.JLabel databaseUrlText;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginText;
    private javax.swing.JMenu menubar1;
    private javax.swing.JMenuItem newWindow;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordText;
    // End of variables declaration//GEN-END:variables
}
